use_frameworks!

platform :ios, '14.0'

install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true,
    :warn_for_unused_master_specs_repo => false

target 'HomeKitLightBulbHelper_Example' do
  pod 'HomeKitLightBulbHelper', :path => '../'

  target 'HomeKitLightBulbHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
